ThirdLesson/dolfin_front

- src/shared/components/atoms/input/BaseInput.vue
- src/shared/components/atoms/input/DefaultInputLine.vue
- src/shared/components/atoms/input/InputBox.vue
- src/shared/components/atoms/input/SubInputLine.vue
- #6 
> Close #6 
- 인풋 공용 컴포넌트 생성
> [Feat]: 인풋 공용 컴포넌트 생성

- src/pages/TestPage.vue
- src/shared/components/molecules/RoundTab.vue
- src/shared/components/molecules/SquareTab.vue
- src/shared/styles/index.css
#16 
- #이슈번호
> Close #16 
- 공용 Tab 컴포넌트 생성
> [Feature]: 공용 Tab 컴포넌트 생성

- src/app/App.vue
- src/app/router.js
- src/pages/SignUpPage.vue
- src/pages/TestPage.vue
- src/shared/components/organisms/Layout.vue
- src/shared/components/organisms/NavBar.vue
#21 
- #이슈번호
> Close #21 
- 레이아웃 템플릿 생성
- 헤더, 네비게이션 바 show 여부 router.js에 설정
> [Feature]: 레이아웃 템플릿 생성

- src/features/exchangeRate/exchageHeader/ui/ExchangeHeader.vue
- #22 
> Close #22
-환율 헤더 컴포넌트 생성
> [Feat] 환율 헤더 컴포넌트 생성

- src/entities/user/user.api.js
- src/features/user/login/services/login.service.js
- src/features/user/login/ui/LoginInput.vue
- src/pages/LoginPage.vue
#28 
- 로그인 페이지 퍼블리싱
- 로그인 페이지 api 연결 로직 작
> [Design]: 로그인 페이지 퍼블리싱

- src/entities/user/user.api.js
- src/features/user/signUp/services/signUp.service.js
- src/features/user/signUp/ui/Step1.vue
- src/features/user/signUp/ui/Step2.vue
- src/features/user/signUp/ui/Step3.vue
- src/features/user/signUp/ui/Step4.vue
- src/pages/SignUpPage.vue
#28 
- #이슈번호
> Close #28 
- 회원가입 퍼블리싱 & api 로직 일부 구현
토스 스타일의 인풋 쌓기가 한국어 기준일 땐 괜찮은데 영어일 때 구현할 수 있을지 불확실해서 일단 구현 안했습니다..
> [Design] 회원가입 페이지 퍼블리싱

- src/features/user/login/ui/LoginInput.vue
- src/features/user/signUp/ui/Step1.vue
- src/features/user/signUp/ui/Step3.vue
- src/features/user/signUp/ui/Step4.vue
- src/pages/SignUpPage.vue
- src/shared/components/atoms/input/TitleInput.vue
- src/shared/components/molecules/Dropdown.vue
#30 
- #이슈번호
> Close #30 
- 국적 선택 드롭다운 추가
- 회원가입 실패 오류 메세지 추가
> [Design]: 회원 가입 페이지 디자인 추가

- src/features/user/login/services/login.service.js
- src/features/user/login/ui/LoginInput.vue
- src/shared/utils/client.js
#34 
- #이슈번호
> Close #34 
- 리프레시 여부 확인을 위한 client.js 추가
- 로그인 로직 구현
> [Feat]: 로그인 로직 구현

- src/entities/map/map.api.js
- src/features/map/services/map.service.js
- src/features/map/ui/MapView.vue
- src/features/map/ui/PlaceInfoModal.vue
- src/pages/MapPage.vue
- #39 
> Close #39
- 스마트맵 페이지 api 연동
> [Feat]: 스마트맵 페이지 api 연동

- package-lock.json
- package.json
- src/entities/user/user.api.js
- src/entities/user/user.store.js
- src/features/user/login/ui/LoginInput.vue
- src/features/user/signUp/services/signUp.service.js
- src/features/user/signUp/ui/Step1.vue
- src/features/user/signUp/ui/Step2.vue
- src/features/user/signUp/ui/Step4.vue
- src/main.js
- src/pages/SignUpPage.vue
- src/shared/components/molecules/Dropdown.vue
- src/shared/utils/client.js
- src/shared/utils/format.js
#40 
- #40
> Close #40
- 날짜 형식 변환 공용 formatDate 함수 생성
- pinia-persist 설
> [Feature] 회원가입 api 연동

- src/entities/trasnsaction/transaction.mock.js
- src/features/user/transaction/ui/TransactionFilter.vue
- src/features/user/transaction/ui/TransactionList.vue
- src/pages/TransactionPage.vue
- #41 
> Close #41
- 거래 내역 페이지 퍼블리싱
> [Design]: 거래 내역 페이지 퍼블리싱

- src/app/router.js
- src/features/user/account/ui/Step1.vue
- src/features/user/account/ui/Step2.vue
- src/pages/AccountPage.vue
- src/pages/ExchangeCheckPage.vue
- src/pages/SignUpPage.vue
- src/shared/components/atoms/input/BoxInput.vue
- src/shared/components/molecules/Header.vue
- src/shared/components/organisms/Layout.vue
- src/shared/components/organisms/PwModal.vue
#42 
- #42
> Close #42
- 계좌 등록 페이지 퍼블리싱
> [Design] 계좌 등록 페이지 퍼블리싱

- src/entities/user/user.api.js
- src/entities/user/user.store.js
- src/features/transaction/history/ui/RecentHistory.vue
- src/features/user/account/services/account.service.js
- src/features/user/account/ui/Wallet.vue
- #이슈번호
> Close #이슈번호
- 메인 페이지 전자지갑 api 연동
> [Feat]: 메인 페이지 전자지갑 api 연동

- src/asset/images.js
- src/features/groupRemit/ui/GroupGuide.vue
- #이슈번호
> Close #이슈번호
- 공동 송금 페이지 수정
> [Fix]: 공동 송금 페이지 수정

- package-lock.json
- package.json
- public/firebase-messaging-sw.js
- src/app/App.vue
- src/entities/user/user.store.js
- src/firebase/config.js
- src/firebase/firebase.service.js
- src/pages/etc/MainPage.vue
- vite.config.js
- #66 
> Close #66 
- firebase 설치
- 알림 기능 구현
> [Feat] 알림 기능 구현

- src/app/router.js
- src/features/user/login/services/login.service.js
- #75 
> Close #75 
- 로그인이 되어 있는 경우 바로 메인 페이지로 이동하도록 설정
> [Feat] 라우터 가드 설정

- src/features/user/account/ui/Step1.vue
- src/features/user/account/ui/Step2.vue
- src/pages/user/AccountPage.vue
- #이슈번호
> Close #이슈번호
- walletId 유무에 따라 계좌등록 페이지 비번 설정 최초 한 번만 하게 하기
- 에러 메세지 백에서 주는 message로 설정
> [Fix] 계좌등록 페이지 수정

- src/features/groupRemit/ui/GroupGuide.vue
- tailwind.config.js
- #91 
> Close #91
- 공동 송금 페이지 애니메이션 추가
> Design: 공동 송금 페이지 애니메이션 추가

- src/entities/exchange/exchange.api.js
- src/features/exchange/exchangeHeader/services/ExchangeHeader.service.js
- src/features/exchange/exchangeHeader/ui/ExchangeHeader.vue
- src/shared/utils/format.js
- #88 
> Close #88 
- 1분마다 한번씩 api 호출
> [Feat] 환율 헤더 api 연동

- index.html
- src/features/user/account/ui/Wallet.vue
- src/pages/etc/OnboardingPage.vue
- src/router/routes.js
- src/shared/styles/index.css
- #107 
> Close #107
- 검색 엔진 최적화, 권장사항 100 달성
- 성능 개선
> [Feature] lighthouse 성능 개선
